name: Build Logic
on:
  workflow_call:
    inputs:
      is_release:
        type: boolean
        default: false
      tag_name:
        type: string

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      build_date: ${{ steps.date.outputs.now }}
    steps:
      - name: Generate Timestamp
        id: date
        run: echo "now=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
  build:
    name: Build (${{ matrix.os }})
    needs: pre-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        arch: [ x64, arm64 ]
        exclude:
          - os: ubuntu-latest
            arch: arm64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          cache: true

      - name: Restore
        run: dotnet restore

      - name: Publish All
        run: |
          dotnet publish ./FloodForge.slnx -c Release -o ./publish-temp --self-contained true -p:PublishReadyToRun=true --no-restore -r ${{ matrix.os == 'ubuntu-latest' && 'linux' || 'win' }}-${{ matrix.arch }}

      - name: Add Nightly Info
        shell: bash
        run: |
          mkdir -p ./publish-temp/mods # Ensure empty mods folder exists
          if [ "${{ inputs.is_release }}" = "false" ]; then
            echo "${{ needs.pre-build.outputs.build_date }}" > ./publish-temp/assets/nightly.txt
          fi

      - name: Prepare & Zip (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cd publish-temp && zip -r ../FloodForge-linux-${{ matrix.arch }}.zip .

      - name: Prepare & Zip (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: 7z a -tzip FloodForge-windows-${{ matrix.arch }}.zip .\publish-temp\*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}-${{ matrix.arch }}
          path: FloodForge-*.zip
          retention-days: 1

  deploy:
    needs: [ build, pre-build ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reset Nightly Tag
        if: inputs.is_release == false
        run: |
          git tag -f nightly
          git push origin nightly --force

      - uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name }}
          name: ${{ inputs.is_release && format('FloodForge {0}', inputs.tag_name) || 'Nightly Development Build' }}
          prerelease: ${{ !inputs.is_release }}
          draft: ${{ inputs.is_release }}
          files: ./artifacts/FloodForge-*.zip
          body: |
            ${{ inputs.is_release && '' || format('BUILD_DATE: {0}', needs.pre-build.outputs.build_date) }}
